In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(tf.__version__)

2.1.0


In [15]:
score_data = np.genfromtxt('scores.csv', delimiter=',')

In [17]:
score_data.view()

array([[nan, nan, nan, nan, nan],
       [90., 81., 95., 89., nan],
       [76., 77., 71., 75., nan],
       ...,
       [94., 90., 89., 91., nan],
       [84., 78., 99., 87., nan],
       [97., 84., 96., 92., nan]])

In [25]:
#math = np.array(score_data['Math'])
math = np.array(score_data[1:, 0:1])
english = np.array(score_data[1:, 1:2])
science = np.array(score_data[1:, 2:3])
print(math)
print()
print(english)
print()
print(science)

[[90.]
 [76.]
 [77.]
 ...
 [94.]
 [84.]
 [97.]]

[[81.]
 [77.]
 [71.]
 ...
 [90.]
 [78.]
 [84.]]

[[95.]
 [71.]
 [97.]
 ...
 [89.]
 [99.]
 [96.]]


In [ ]:
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

In [ ]:
learning_rate = 0.00001

In [ ]:
hypothesis = tf.multiply(math, w1)
for i in hypothesis:
    print('{:10.3f}'.format(i))

In [ ]:
for i in range(1000):
    with tf.GradientTape() as tape:
        hypothesis = math * w1 + english * w2 + science * w3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - avg_score))
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    w1.assign_sub(learning_rate * w1_grad) # W1 -= learning_rate * w1_grad
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 10 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

In [ ]:
hypothesis = math * w1
print(hypothesis)

In [ ]:
hypothesis = tf.multiply(math, w1)

for i in hypothesis:
    print('{:10.3f}'.format(i))