In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(tf.__version__)

2.1.0


In [2]:
score_data = np.genfromtxt('scores.csv', delimiter=',', dtype = np.float32)
print(score_data.dtype)

float32


In [ ]:
score_data.view()

In [ ]:
#math = np.array(score_data['Math'])
x1 = np.array(score_data[1:, 0:1])
x2 = np.array(score_data[1:, 1:2])
x3 = np.array(score_data[1:, 2:3])
Y = np.array(score_data[1:, -1:]) #실제 값들
print(x1)
print()
print(x2)
print()
print(x3)
print()
print(Y)

In [ ]:
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

In [ ]:
print(w1.shape)

In [3]:
learning_rate = 0.000001

In [ ]:
hypothesis =x1 * w1
for i in hypothesis:
    print(i)

In [ ]:
x = tf.ones((2, 2))

with tf.GradientTape() as t:
  y = tf.reduce_sum(x)
  print (y)
  z = tf.multiply(y, y)
  print(z)

# 테이프 사용하여 중간값 y에 대한 도함수를 계산합니다. 
dz_dy = t.gradient(z, y)
print(dz_dy)

In [ ]:
for i in range(10000):
    with tf.GradientTape() as tape:
        hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y)) #가설값과 실제값의 차이(cost)
    
    #cost의 새로운 기울기
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    #새로 구한 기울기값으로 weight값들 update
    w1.assign_sub(learning_rate * w1_grad) # W1 -= learning_rate * w1_grad
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy())) #차이(cost)가 작아져야 성공적인것이다

In [15]:
X = score_data[1:, :-1]
Y = score_data[1:, [-1]]
print(X)
print(Y)

[[90. 81. 95.]
 [76. 77. 71.]
 [77. 71. 97.]
 ...
 [94. 90. 89.]
 [84. 78. 99.]
 [97. 84. 96.]]
[[281.]
 [235.]
 [257.]
 ...
 [290.]
 [271.]
 [291.]]


In [16]:
W = tf.Variable(tf.random.normal([3, 1])) #weight matrix (x_data의 column이 3개)
b = tf.Variable(tf.random.normal([1]))

def predict(X):
    return tf.matmul(X, W) + b #bias는 생략가능
print(predict(X))

tf.Tensor(
[[36.649754]
 [41.322548]
 [27.355818]
 ...
 [46.350155]
 [32.665966]
 [38.93132 ]], shape=(10000, 1), dtype=float32)


In [22]:
learning_rate = 0.00001

In [24]:
for i in range(10000):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean(tf.square(predict(X) - Y)) #가설값과 실제값의 차이(cost)
    
    #cost의 새로운 기울기
    W_grad, b_grad = tape.gradient(cost, [W, b])
    
    #새로 구한 기울기값으로 weight값들 update
    W.assign_sub(learning_rate * W_grad) # W1 -= learning_rate * w1_grad
    b.assign_sub(learning_rate * b_grad)
    
    #차이(cost)가 작아져야 성공적인것이다(0에 가까워질수록 정확도 상승)
    if i % 1000 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy())) 

    0 |      10.9531
 1000 |      10.9272
 2000 |      10.9084
 3000 |      10.8948
 4000 |      10.8850
 5000 |      10.8778
 6000 |      10.8727
 7000 |      10.8689
 8000 |      10.8662
 9000 |      10.8642


In [26]:
x1 = float(input())
x2 = float(input())
x3 = float(input())
input_x = np.array([[x1, x2, x3]], dtype = np.float32)
print(predict(input_x).numpy())

76
77
71
[[237.12062]]
